{
  "nodes": [
    {
      "parameters": {
        "httpMethod": "GET",
        "path": "flyio-switcher"
      },
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{ $json.query.action }}",
              "operation": "equal",
              "value2": "start"
            }
          ]
        }
      },
      "name": "Switch",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        450,
        300
      ]
    },
    {
      "parameters": {
        "url": "={{ `https://api.fly.io/v1/apps/${$json.query.app_name}/machines/${$json.query.machine_id}/start` }}",
        "method": "POST",
        "authentication": "headerAuth",
        "headerAuth": {
          "headerName": "Authorization",
          "headerValue": "Bearer {{$secret.flyApiToken}}",
          "headerType": "standard"
        },
        "sendHeaders": true
      },
      "name": "Fly.io Start Machine",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        650,
        200
      ]
    },
    {
      "parameters": {
        "url": "={{ `https://api.fly.io/v1/apps/${$json.query.app_name}/machines/${$json.query.machine_id}/stop` }}",
        "method": "POST",
        "authentication": "headerAuth",
        "headerAuth": {
          "headerName": "Authorization",
          "headerValue": "Bearer {{$secret.flyApiToken}}",
          "headerType": "standard"
        },
        "sendHeaders": true
      },
      "name": "Fly.io Stop Machine",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        650,
        400
      ]
    }
  ],
  "connections": {
    "Webhook": {
      "main": [
        [
          {
            "node": "Switch",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Switch": {
      "main": [
        [
          {
            "node": "Fly.io Start Machine",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Fly.io Stop Machine",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}