cat > .github/workflows/fly-deploy.yml << 'EOF'
name: 🚀 Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions@1.1
        with:
          version: latest

      - name: Deploy to Fly.io
        run: fly deploy --remote-only -a n8nxio
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
EOF
